const SHIPPING_THRESHOLD = 150;
const SHIPPING_FEE = 12;
const TAX_RATE = 0.08;

const ADMIN = {
  email: "admin@soleil.com",
  password: "admin123",
};

const SHAPES = ["Aviator", "Wayfarer", "Round", "Cat-eye", "Sport", "Rectangle", "Oversized"];
const GENDERS = ["Unisex", "Women", "Men"];
const STATUSES = ["paid", "processing", "shipped", "delivered", "cancelled"];

const SEED_PRODUCTS = [
  {
    id: "p-solstice",
    slug: "solstice-aviator",
    name: "Solstice Aviator",
    price: 189,
    compareAt: 230,
    description:
      "A refined take on the classic aviator. Gold-tone metal, warm gradient lenses, and a silhouette that belongs in every summer wardrobe.",
    details: ["UV400 protection", "Polarized lenses", "Adjustable nose pads", "Includes case & cloth"],
    shape: "Aviator",
    gender: "Unisex",
    color: "Gold",
    frame: "Gold metal",
    lens: "Brown gradient",
    material: "Stainless steel",
    stock: 24,
    featured: true,
    image: "products/solstice.jpg",
    createdAt: "2026-03-12",
  },
  {
    id: "p-noir",
    slug: "noir-wayfarer",
    name: "Noir Wayfarer",
    price: 149,
    description: "Matte black acetate with smoke lenses. The everyday frame — sharp, quiet, and endlessly wearable.",
    details: ["UV400 protection", "Acetate frame", "Spring hinges", "Includes case & cloth"],
    shape: "Wayfarer",
    gender: "Unisex",
    color: "Black",
    frame: "Matte black acetate",
    lens: "Smoke",
    material: "Italian acetate",
    stock: 36,
    featured: true,
    image: "products/noir.jpg",
    createdAt: "2026-02-04",
  },
  {
    id: "p-luna",
    slug: "luna-round",
    name: "Luna Round",
    price: 169,
    description: "Thin gold wire and amber lenses. A lighter, more lyrical circle — made for long afternoons.",
    details: ["UV400 protection", "Lightweight wire", "Comfort temples", "Includes case & cloth"],
    shape: "Round",
    gender: "Unisex",
    color: "Gold",
    frame: "Gold wire",
    lens: "Amber",
    material: "Titanium alloy",
    stock: 18,
    featured: true,
    image: "products/luna.jpg",
    createdAt: "2026-04-01",
  },
  {
    id: "p-isolde",
    slug: "isolde-cateye",
    name: "Isolde Cat-eye",
    price: 179,
    description: "Tortoise acetate lifted at the corners, olive lenses. Vintage glamour without the costume.",
    details: ["UV400 protection", "Hand-polished acetate", "Category 3 lenses", "Includes case & cloth"],
    shape: "Cat-eye",
    gender: "Women",
    color: "Tortoise",
    frame: "Tortoise acetate",
    lens: "Olive",
    material: "Italian acetate",
    stock: 14,
    featured: true,
    image: "products/isolde.jpg",
    createdAt: "2026-01-22",
  },
  {
    id: "p-apex",
    slug: "apex-sport",
    name: "Apex Sport",
    price: 199,
    description: "Wraparound lines, gunmetal frame, mirrored blue lenses. Built for glare, speed, and open road.",
    details: ["UV400 protection", "Polarized mirror", "Rubberized grip", "Includes sport case"],
    shape: "Sport",
    gender: "Men",
    color: "Gunmetal",
    frame: "Gunmetal wrap",
    lens: "Blue mirror",
    material: "TR-90 + metal",
    stock: 20,
    featured: false,
    image: "products/apex.jpg",
    createdAt: "2026-05-08",
  },
  {
    id: "p-dune",
    slug: "dune-rectangle",
    name: "Dune Rectangle",
    price: 219,
    compareAt: 260,
    description: "Champagne metal and warm brown lenses in a generous rectangle. Quiet luxury, full coverage.",
    details: ["UV400 protection", "Oversized fit", "Polarized lenses", "Includes case & cloth"],
    shape: "Rectangle",
    gender: "Unisex",
    color: "Champagne",
    frame: "Champagne metal",
    lens: "Warm brown",
    material: "Stainless steel",
    stock: 11,
    featured: true,
    image: "products/dune.jpg",
    createdAt: "2026-03-28",
  },
  {
    id: "p-meridian",
    slug: "meridian-pilot",
    name: "Meridian Pilot",
    price: 189,
    description: "Silver double-bridge pilot with light gray lenses. Cooler than gold, just as iconic.",
    details: ["UV400 protection", "Double bridge", "Adjustable pads", "Includes case & cloth"],
    shape: "Aviator",
    gender: "Men",
    color: "Silver",
    frame: "Silver metal",
    lens: "Light gray",
    material: "Stainless steel",
    stock: 16,
    featured: false,
    image: "products/meridian.jpg",
    createdAt: "2026-02-18",
  },
  {
    id: "p-halo",
    slug: "halo-clear",
    name: "Halo Clear",
    price: 159,
    description: "Translucent acetate that almost disappears. A modern frame for faces that want air, not weight.",
    details: ["UV400 protection", "Crystal acetate", "Pale smoke lenses", "Includes case & cloth"],
    shape: "Rectangle",
    gender: "Unisex",
    color: "Clear",
    frame: "Clear acetate",
    lens: "Pale smoke",
    material: "Italian acetate",
    stock: 22,
    featured: false,
    image: "products/halo.jpg",
    createdAt: "2026-06-02",
  },
  {
    id: "p-alba",
    slug: "alba-pearl",
    name: "Alba Pearl",
    price: 169,
    description: "Pearl acetate, rose-gold temples, blush-tinted lenses. Soft, precise, and a little romantic.",
    details: ["UV400 protection", "Pearl acetate", "Rose-gold temples", "Includes case & cloth"],
    shape: "Rectangle",
    gender: "Women",
    color: "Pearl",
    frame: "Pearl acetate",
    lens: "Blush",
    material: "Italian acetate",
    stock: 13,
    featured: false,
    image: "products/alba.jpg",
    createdAt: "2026-04-19",
  },
  {
    id: "p-eclipse",
    slug: "eclipse-oversized",
    name: "Eclipse Oversized",
    price: 229,
    description: "Bold black acetate, full dark lenses. A statement shade that still feels considered.",
    details: ["UV400 protection", "Thick acetate", "Category 3 lenses", "Includes case & cloth"],
    shape: "Oversized",
    gender: "Unisex",
    color: "Black",
    frame: "Black acetate",
    lens: "Dark smoke",
    material: "Italian acetate",
    stock: 9,
    featured: true,
    image: "products/eclipse.jpg",
    createdAt: "2026-01-09",
  },
  {
    id: "p-velvet",
    slug: "velvet-bordeaux",
    name: "Velvet Bordeaux",
    price: 189,
    description: "Wine-dark acetate and brown lenses. Evening color, daytime ease.",
    details: ["UV400 protection", "Hand-finished acetate", "Warm brown lenses", "Includes case & cloth"],
    shape: "Rectangle",
    gender: "Women",
    color: "Bordeaux",
    frame: "Wine acetate",
    lens: "Brown",
    material: "Italian acetate",
    stock: 12,
    featured: false,
    image: "products/velvet.jpg",
    createdAt: "2026-05-21",
  },
];

const SEED_ORDERS = [
  {
    id: "SL-24081101",
    items: [
      { productId: "p-solstice", name: "Solstice Aviator", price: 189, qty: 1, image: "products/solstice.jpg" },
    ],
    customer: {
      firstName: "Amelia",
      lastName: "Reyes",
      email: "amelia@example.com",
      phone: "+1 415 555 0198",
      address: "88 Market Street",
      city: "San Francisco",
      zip: "94103",
      country: "United States",
    },
    last4: "4242",
    cardBrand: "Visa",
    subtotal: 189,
    shipping: 0,
    tax: 15.12,
    total: 204.12,
    status: "processing",
    createdAt: "2026-08-08T14:22:00.000Z",
  },
  {
    id: "SL-24080614",
    items: [
      { productId: "p-isolde", name: "Isolde Cat-eye", price: 179, qty: 1, image: "products/isolde.jpg" },
      { productId: "p-noir", name: "Noir Wayfarer", price: 149, qty: 1, image: "products/noir.jpg" },
    ],
    customer: {
      firstName: "James",
      lastName: "Kline",
      email: "james.k@example.com",
      phone: "+1 212 555 0144",
      address: "19 Mercer Street",
      city: "New York",
      zip: "10013",
      country: "United States",
    },
    last4: "1881",
    cardBrand: "Mastercard",
    subtotal: 328,
    shipping: 0,
    tax: 26.24,
    total: 354.24,
    status: "shipped",
    createdAt: "2026-08-04T09:10:00.000Z",
  },
];
